./myanalysisprogram.sh: line 8: /reads-1: No such file or directory
./myanalysisprogram.sh: line 8: /reads-2: No such file or directory
./myanalysisprogram.sh: line 8: /reads-3: No such file or directory
./myanalysisprogram.sh: line 8: /reads-4: No such file or directory
./myanalysisprogram.sh: line 8: /reads-9: No such file or directory
./myanalysisprogram.sh: line 8: /reads-5: No such file or directory
./myanalysisprogram.sh: line 8: /reads-6: No such file or directory
./myanalysisprogram.sh: line 8: /reads-7: No such file or directory
./myanalysisprogram.sh: line 8: /reads-10: No such file or directory
./myanalysisprogram.sh: line 8: /reads-11: No such file or directory
./myanalysisprogram.sh: line 8: /reads-12: No such file or directory
./myanalysisprogram.sh: line 8: /reads-8: No such file or directory
./myanalysisprogram.sh: line 8: /reads-21: No such file or directory
./myanalysisprogram.sh: line 8: /reads-29: No such file or directory
./myanalysisprogram.sh: line 8: /reads-25: No such file or directory
./myanalysisprogram.sh: line 8: /reads-33: No such file or directory
./myanalysisprogram.sh: line 8: /reads-14: No such file or directory
./myanalysisprogram.sh: line 8: /reads-15: No such file or directory
./myanalysisprogram.sh: line 8: /reads-40: No such file or directory
./myanalysisprogram.sh: line 8: /reads-43: No such file or directory
./myanalysisprogram.sh: line 8: /reads-41: No such file or directory
./myanalysisprogram.sh: line 8: /reads-13: No such file or directory
./myanalysisprogram.sh: line 8: /reads-35: No such file or directory
./myanalysisprogram.sh: line 8: /reads-24: No such file or directory
./myanalysisprogram.sh: line 8: /reads-28: No such file or directory
./myanalysisprogram.sh: line 8: /reads-34: No such file or directory
./myanalysisprogram.sh: line 8: /reads-32: No such file or directory
./myanalysisprogram.sh: line 8: /reads-16: No such file or directory
./myanalysisprogram.sh: line 8: /reads-37: No such file or directory
./myanalysisprogram.sh: line 8: /reads-39: No such file or directory
./myanalysisprogram.sh: line 8: /reads-38: No such file or directory
./myanalysisprogram.sh: line 8: /reads-42: No such file or directory
./myanalysisprogram.sh: line 8: /reads-31: No such file or directory
./myanalysisprogram.sh: line 8: /reads-36: No such file or directory
./myanalysisprogram.sh: line 8: /reads-23: No such file or directory
./myanalysisprogram.sh: line 8: /reads-20: No such file or directory
./myanalysisprogram.sh: line 8: /reads-27: No such file or directory
./myanalysisprogram.sh: line 8: /reads-19: No such file or directory
./myanalysisprogram.sh: line 8: /reads-17: No such file or directory
./myanalysisprogram.sh: line 8: /reads-18: No such file or directory
./myanalysisprogram.sh: line 8: /reads-44: No such file or directory
./myanalysisprogram.sh: line 8: /reads-46: No such file or directory
./myanalysisprogram.sh: line 8: /reads-45: No such file or directory
./myanalysisprogram.sh: line 8: /reads-22: No such file or directory
./myanalysisprogram.sh: line 8: /reads-30: No such file or directory
./myanalysisprogram.sh: line 8: /reads-26: No such file or directory
./myanalysisprogram.sh: line 8: /reads-53: No such file or directory
./myanalysisprogram.sh: line 8: /reads-62: No such file or directory
./myanalysisprogram.sh: line 8: /reads-56: No such file or directory
./myanalysisprogram.sh: line 8: /reads-54: No such file or directory
./myanalysisprogram.sh: line 8: /reads-55: No such file or directory
./myanalysisprogram.sh: line 8: /reads-57: No such file or directory
./myanalysisprogram.sh: line 8: /reads-52: No such file or directory
./myanalysisprogram.sh: line 8: /reads-51: No such file or directory
./myanalysisprogram.sh: line 8: /reads-50: No such file or directory
./myanalysisprogram.sh: line 8: /reads-58: No such file or directory
./myanalysisprogram.sh: line 8: /reads-60: No such file or directory
./myanalysisprogram.sh: line 8: /reads-67: No such file or directory
./myanalysisprogram.sh: line 8: /reads-69: No such file or directory
./myanalysisprogram.sh: line 8: /reads-65: No such file or directory
./myanalysisprogram.sh: line 8: /reads-59: No such file or directory
./myanalysisprogram.sh: line 8: /reads-47: No such file or directory
./myanalysisprogram.sh: line 8: /reads-48: No such file or directory
./myanalysisprogram.sh: line 8: /reads-49: No such file or directory
./myanalysisprogram.sh: line 8: /reads-63: No such file or directory
./myanalysisprogram.sh: line 8: /reads-75: No such file or directory
./myanalysisprogram.sh: line 8: /reads-61: No such file or directory
./myanalysisprogram.sh: line 8: /reads-68: No such file or directory
./myanalysisprogram.sh: line 8: /reads-78: No such file or directory
./myanalysisprogram.sh: line 8: /reads-66: No such file or directory
./myanalysisprogram.sh: line 8: /reads-71: No such file or directory
./myanalysisprogram.sh: line 8: /reads-74: No such file or directory
./myanalysisprogram.sh: line 8: /reads-70: No such file or directory
./myanalysisprogram.sh: line 8: /reads-64: No such file or directory
./myanalysisprogram.sh: line 8: /reads-82: No such file or directory
./myanalysisprogram.sh: line 8: /reads-76: No such file or directory
./myanalysisprogram.sh: line 8: /reads-85: No such file or directory
./myanalysisprogram.sh: line 8: /reads-89: No such file or directory
./myanalysisprogram.sh: line 8: /reads-80: No such file or directory
./myanalysisprogram.sh: line 8: /reads-72: No such file or directory
./myanalysisprogram.sh: line 8: /reads-79: No such file or directory
./myanalysisprogram.sh: line 8: /reads-87: No such file or directory
./myanalysisprogram.sh: line 8: /reads-73: No such file or directory
./myanalysisprogram.sh: line 8: /reads-83: No such file or directory
./myanalysisprogram.sh: line 8: /reads-81: No such file or directory
./myanalysisprogram.sh: line 8: /reads-84: No such file or directory
./myanalysisprogram.sh: line 8: /reads-77: No such file or directory
./myanalysisprogram.sh: line 8: /reads-94: No such file or directory
./myanalysisprogram.sh: line 8: /reads-90: No such file or directory
./myanalysisprogram.sh: line 8: /reads-100: No such file or directory
./myanalysisprogram.sh: line 8: /reads-97: No such file or directory
./myanalysisprogram.sh: line 8: /reads-96: No such file or directory
./myanalysisprogram.sh: line 8: /reads-86: No such file or directory
./myanalysisprogram.sh: line 8: /reads-98: No such file or directory
./myanalysisprogram.sh: line 8: /reads-92: No such file or directory
./myanalysisprogram.sh: line 8: /reads-95: No such file or directory
./myanalysisprogram.sh: line 8: /reads-99: No such file or directory
./myanalysisprogram.sh: line 8: /reads-88: No such file or directory
./myanalysisprogram.sh: line 8: /reads-93: No such file or directory
./myanalysisprogram.sh: line 8: /reads-91: No such file or directory
./myanalysisprogram.sh: line 8: /reads-1: No such file or directory
./myanalysisprogram.sh: line 8: /reads-2: No such file or directory
./myanalysisprogram.sh: line 8: /reads-3: No such file or directory
./myanalysisprogram.sh: line 8: /reads-4: No such file or directory
./myanalysisprogram.sh: line 8: /reads-5: No such file or directory
./myanalysisprogram.sh: line 8: /reads-7: No such file or directory
./myanalysisprogram.sh: line 8: /reads-12: No such file or directory
./myanalysisprogram.sh: line 8: /reads-11: No such file or directory
./myanalysisprogram.sh: line 8: /reads-14: No such file or directory
./myanalysisprogram.sh: line 8: /reads-6: No such file or directory
./myanalysisprogram.sh: line 8: /reads-8: No such file or directory
./myanalysisprogram.sh: line 8: /reads-15: No such file or directory
./myanalysisprogram.sh: line 8: /reads-17: No such file or directory
./myanalysisprogram.sh: line 8: /reads-16: No such file or directory
./myanalysisprogram.sh: line 8: /reads-9: No such file or directory
./myanalysisprogram.sh: line 8: /reads-18: No such file or directory
./myanalysisprogram.sh: line 8: /reads-19: No such file or directory
./myanalysisprogram.sh: line 8: /reads-21: No such file or directory
./myanalysisprogram.sh: line 8: /reads-13: No such file or directory
./myanalysisprogram.sh: line 8: /reads-22: No such file or directory
./myanalysisprogram.sh: line 8: /reads-24: No such file or directory
./myanalysisprogram.sh: line 8: /reads-23: No such file or directory
./myanalysisprogram.sh: line 8: /reads-20: No such file or directory
./myanalysisprogram.sh: line 8: /reads-31: No such file or directory
./myanalysisprogram.sh: line 8: /reads-10: No such file or directory
./myanalysisprogram.sh: line 8: /reads-28: No such file or directory
./myanalysisprogram.sh: line 8: /reads-26: No such file or directory
./myanalysisprogram.sh: line 8: /reads-41: No such file or directory
./myanalysisprogram.sh: line 8: /reads-25: No such file or directory
./myanalysisprogram.sh: line 8: /reads-60: No such file or directory
./myanalysisprogram.sh: line 8: /reads-30: No such file or directory
./myanalysisprogram.sh: line 8: /reads-53: No such file or directory
./myanalysisprogram.sh: line 8: /reads-55: No such file or directory
./myanalysisprogram.sh: line 8: /reads-50: No such file or directory
./myanalysisprogram.sh: line 8: /reads-51: No such file or directory
./myanalysisprogram.sh: line 8: /reads-43: No such file or directory
./myanalysisprogram.sh: line 8: /reads-39: No such file or directory
./myanalysisprogram.sh: line 8: /reads-54: No such file or directory
./myanalysisprogram.sh: line 8: /reads-29: No such file or directory
./myanalysisprogram.sh: line 8: /reads-35: No such file or directory
./myanalysisprogram.sh: line 8: /reads-68: No such file or directory
./myanalysisprogram.sh: line 8: /reads-27: No such file or directory
./myanalysisprogram.sh: line 8: /reads-57: No such file or directory
./myanalysisprogram.sh: line 8: /reads-37: No such file or directory
./myanalysisprogram.sh: line 8: /reads-45: No such file or directory
./myanalysisprogram.sh: line 8: /reads-64: No such file or directory
./myanalysisprogram.sh: line 8: /reads-71: No such file or directory
./myanalysisprogram.sh: line 8: /reads-65: No such file or directory
./myanalysisprogram.sh: line 8: /reads-59: No such file or directory
./myanalysisprogram.sh: line 8: /reads-62: No such file or directory
./myanalysisprogram.sh: line 8: /reads-61: No such file or directory
./myanalysisprogram.sh: line 8: /reads-36: No such file or directory
./myanalysisprogram.sh: line 8: /reads-52: No such file or directory
./myanalysisprogram.sh: line 8: /reads-38: No such file or directory
./myanalysisprogram.sh: line 8: /reads-42: No such file or directory
./myanalysisprogram.sh: line 8: /reads-72: No such file or directory
./myanalysisprogram.sh: line 8: /reads-75: No such file or directory
./myanalysisprogram.sh: line 8: /reads-33: No such file or directory
./myanalysisprogram.sh: line 8: /reads-48: No such file or directory
./myanalysisprogram.sh: line 8: /reads-63: No such file or directory
./myanalysisprogram.sh: line 8: /reads-74: No such file or directory
./myanalysisprogram.sh: line 8: /reads-49: No such file or directory
./myanalysisprogram.sh: line 8: /reads-47: No such file or directory
./myanalysisprogram.sh: line 8: /reads-32: No such file or directory
./myanalysisprogram.sh: line 8: /reads-46: No such file or directory
./myanalysisprogram.sh: line 8: /reads-44: No such file or directory
./myanalysisprogram.sh: line 8: /reads-34: No such file or directory
./myanalysisprogram.sh: line 8: /reads-97: No such file or directory
./myanalysisprogram.sh: line 8: /reads-40: No such file or directory
./myanalysisprogram.sh: line 8: /reads-80: No such file or directory
./myanalysisprogram.sh: line 8: /reads-88: No such file or directory
./myanalysisprogram.sh: line 8: /reads-56: No such file or directory
./myanalysisprogram.sh: line 8: /reads-95: No such file or directory
./myanalysisprogram.sh: line 8: /reads-78: No such file or directory
./myanalysisprogram.sh: line 8: /reads-90: No such file or directory
./myanalysisprogram.sh: line 8: /reads-87: No such file or directory
./myanalysisprogram.sh: line 8: /reads-83: No such file or directory
./myanalysisprogram.sh: line 8: /reads-79: No such file or directory
./myanalysisprogram.sh: line 8: /reads-58: No such file or directory
./myanalysisprogram.sh: line 8: /reads-66: No such file or directory
./myanalysisprogram.sh: line 8: /reads-69: No such file or directory
./myanalysisprogram.sh: line 8: /reads-70: No such file or directory
./myanalysisprogram.sh: line 8: /reads-99: No such file or directory
./myanalysisprogram.sh: line 8: /reads-85: No such file or directory
./myanalysisprogram.sh: line 8: /reads-96: No such file or directory
./myanalysisprogram.sh: line 8: /reads-84: No such file or directory
./myanalysisprogram.sh: line 8: /reads-81: No such file or directory
./myanalysisprogram.sh: line 8: /reads-77: No such file or directory
./myanalysisprogram.sh: line 8: /reads-82: No such file or directory
./myanalysisprogram.sh: line 8: /reads-86: No such file or directory
./myanalysisprogram.sh: line 8: /reads-91: No such file or directory
./myanalysisprogram.sh: line 8: /reads-89: No such file or directory
./myanalysisprogram.sh: line 8: /reads-67: No such file or directory
./myanalysisprogram.sh: line 8: /reads-76: No such file or directory
./myanalysisprogram.sh: line 8: /reads-92: No such file or directory
./myanalysisprogram.sh: line 8: /reads-98: No such file or directory
./myanalysisprogram.sh: line 8: /reads-100: No such file or directory
./myanalysisprogram.sh: line 8: /reads-73: No such file or directory
./myanalysisprogram.sh: line 8: /reads-93: No such file or directory
./myanalysisprogram.sh: line 8: /reads-94: No such file or directory
./myanalysisprogram.sh: line 8: /reads-1: No such file or directory
./myanalysisprogram.sh: line 8: /reads-2: No such file or directory
./myanalysisprogram.sh: line 8: /reads-3: No such file or directory
./myanalysisprogram.sh: line 8: /reads-4: No such file or directory
./myanalysisprogram.sh: line 8: /reads-5: No such file or directory
./myanalysisprogram.sh: line 8: /reads-7: No such file or directory
./myanalysisprogram.sh: line 8: /reads-21: No such file or directory
./myanalysisprogram.sh: line 8: /reads-20: No such file or directory
./myanalysisprogram.sh: line 8: /reads-6: No such file or directory
./myanalysisprogram.sh: line 8: /reads-8: No such file or directory
./myanalysisprogram.sh: line 8: /reads-18: No such file or directory
./myanalysisprogram.sh: line 8: /reads-15: No such file or directory
./myanalysisprogram.sh: line 8: /reads-14: No such file or directory
./myanalysisprogram.sh: line 8: /reads-12: No such file or directory
./myanalysisprogram.sh: line 8: /reads-11: No such file or directory
./myanalysisprogram.sh: line 8: /reads-10: No such file or directory
./myanalysisprogram.sh: line 8: /reads-9: No such file or directory
./myanalysisprogram.sh: line 8: /reads-13: No such file or directory
./myanalysisprogram.sh: line 8: /reads-16: No such file or directory
./myanalysisprogram.sh: line 8: /reads-17: No such file or directory
./myanalysisprogram.sh: line 8: /reads-19: No such file or directory
./myanalysisprogram.sh: line 8: /reads-23: No such file or directory
./myanalysisprogram.sh: line 8: /reads-24: No such file or directory
./myanalysisprogram.sh: line 8: /reads-26: No such file or directory
./myanalysisprogram.sh: line 8: /reads-43: No such file or directory
./myanalysisprogram.sh: line 8: /reads-39: No such file or directory
./myanalysisprogram.sh: line 8: /reads-41: No such file or directory
./myanalysisprogram.sh: line 8: /reads-44: No such file or directory
./myanalysisprogram.sh: line 8: /reads-46: No such file or directory
./myanalysisprogram.sh: line 8: /reads-47: No such file or directory
./myanalysisprogram.sh: line 8: /reads-37: No such file or directory
./myanalysisprogram.sh: line 8: /reads-36: No such file or directory
./myanalysisprogram.sh: line 8: /reads-40: No such file or directory
./myanalysisprogram.sh: line 8: /reads-48: No such file or directory
./myanalysisprogram.sh: line 8: /reads-53: No such file or directory
./myanalysisprogram.sh: line 8: /reads-32: No such file or directory
./myanalysisprogram.sh: line 8: /reads-50: No such file or directory
./myanalysisprogram.sh: line 8: /reads-54: No such file or directory
./myanalysisprogram.sh: line 8: /reads-51: No such file or directory
./myanalysisprogram.sh: line 8: /reads-56: No such file or directory
./myanalysisprogram.sh: line 8: /reads-58: No such file or directory
./myanalysisprogram.sh: line 8: /reads-33: No such file or directory
./myanalysisprogram.sh: line 8: /reads-35: No such file or directory
./myanalysisprogram.sh: line 8: /reads-57: No such file or directory
./myanalysisprogram.sh: line 8: /reads-65: No such file or directory
./myanalysisprogram.sh: line 8: /reads-34: No such file or directory
./myanalysisprogram.sh: line 8: /reads-38: No such file or directory
./myanalysisprogram.sh: line 8: /reads-42: No such file or directory
./myanalysisprogram.sh: line 8: /reads-45: No such file or directory
./myanalysisprogram.sh: line 8: /reads-22: No such file or directory
./myanalysisprogram.sh: line 8: /reads-29: No such file or directory
./myanalysisprogram.sh: line 8: /reads-28: No such file or directory
./myanalysisprogram.sh: line 8: /reads-30: No such file or directory
./myanalysisprogram.sh: line 8: /reads-31: No such file or directory
./myanalysisprogram.sh: line 8: /reads-27: No such file or directory
./myanalysisprogram.sh: line 8: /reads-25: No such file or directory
./myanalysisprogram.sh: line 8: /reads-52: No such file or directory
./myanalysisprogram.sh: line 8: /reads-55: No such file or directory
./myanalysisprogram.sh: line 8: /reads-63: No such file or directory
./myanalysisprogram.sh: line 8: /reads-64: No such file or directory
./myanalysisprogram.sh: line 8: /reads-49: No such file or directory
./myanalysisprogram.sh: line 8: /reads-60: No such file or directory
./myanalysisprogram.sh: line 8: /reads-59: No such file or directory
./myanalysisprogram.sh: line 8: /reads-61: No such file or directory
./myanalysisprogram.sh: line 8: /reads-62: No such file or directory
./myanalysisprogram.sh: line 8: /reads-71: No such file or directory
./myanalysisprogram.sh: line 8: /reads-77: No such file or directory
./myanalysisprogram.sh: line 8: /reads-74: No such file or directory
./myanalysisprogram.sh: line 8: /reads-66: No such file or directory
./myanalysisprogram.sh: line 8: /reads-68: No such file or directory
./myanalysisprogram.sh: line 8: /reads-67: No such file or directory
./myanalysisprogram.sh: line 8: /reads-79: No such file or directory
./myanalysisprogram.sh: line 8: /reads-84: No such file or directory
./myanalysisprogram.sh: line 8: /reads-76: No such file or directory
./myanalysisprogram.sh: line 8: /reads-73: No such file or directory
./myanalysisprogram.sh: line 8: /reads-91: No such file or directory
./myanalysisprogram.sh: line 8: /reads-93: No such file or directory
./myanalysisprogram.sh: line 8: /reads-82: No such file or directory
./myanalysisprogram.sh: line 8: /reads-80: No such file or directory
./myanalysisprogram.sh: line 8: /reads-94: No such file or directory
./myanalysisprogram.sh: line 8: /reads-92: No such file or directory
./myanalysisprogram.sh: line 8: /reads-90: No such file or directory
./myanalysisprogram.sh: line 8: /reads-99: No such file or directory
./myanalysisprogram.sh: line 8: /reads-100: No such file or directory
./myanalysisprogram.sh: line 8: /reads-97: No such file or directory
./myanalysisprogram.sh: line 8: /reads-86: No such file or directory
./myanalysisprogram.sh: line 8: /reads-98: No such file or directory
./myanalysisprogram.sh: line 8: /reads-87: No such file or directory
./myanalysisprogram.sh: line 8: /reads-88: No such file or directory
./myanalysisprogram.sh: line 8: /reads-89: No such file or directory
./myanalysisprogram.sh: line 8: /reads-85: No such file or directory
./myanalysisprogram.sh: line 8: /reads-81: No such file or directory
./myanalysisprogram.sh: line 8: /reads-83: No such file or directory
./myanalysisprogram.sh: line 8: /reads-75: No such file or directory
./myanalysisprogram.sh: line 8: /reads-78: No such file or directory
./myanalysisprogram.sh: line 8: /reads-70: No such file or directory
./myanalysisprogram.sh: line 8: /reads-95: No such file or directory
./myanalysisprogram.sh: line 8: /reads-72: No such file or directory
./myanalysisprogram.sh: line 8: /reads-69: No such file or directory
./myanalysisprogram.sh: line 8: /reads-96: No such file or directory
